sudo: required
dist: trusty
language: cpp

services:
  - docker

branches:
  only:
    - master
    - develop

before_install:
  - docker build -t travis-build -f infrastructure/tools/Dockerfile .

script:
  # Common style check
  - docker run --rm travis-build infrastructure/tools/checkstyle.sh $TRAVIS_COMMIT_RANGE
  # Run tests
  - docker run --rm travis-build /bin/bash -c "fab test_all"
