sudo: required
dist: trusty
language: cpp

services:
  - docker

branches:
  only:
    - master
    - develop

before_install:
  - docker build -t travis-build -f tools/Dockerfile .

script:
  # Common style check
  - docker run --rm travis-build tools/checkstyle.sh $TRAVIS_COMMIT_RANGE
  # Test whole project with pylint (can find issues in multiple files)
  - docker run --rm travis-build /bin/bash -c "pylint --rcfile=.pylintrc ./pylua"
  # Run tests
  - docker run --rm travis-build /bin/bash -c "pytest"
